#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("catGame.Resource", IsApplication=true)]

namespace catGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dark2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int grey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int grey2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int indigo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int indigo2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int orange = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int orange2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int purple = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int purple2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int red = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int red2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int turquoise = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int turquoise2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int yellow = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int yellow2 = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int button1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int button3 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int button4 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button5 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int button6 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int button7 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button8 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button9 = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int frameLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tableRow1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow3 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int textView1 = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int chord = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
